### ISSUE TITLE
왜 글 삭제시에 patch 메소드를 사용하셨나요?

### ISSUE THREAD

**Issue by yzkim9501** [fnrkp089/Han_M_1#1]
코드 잘 보고 갑니다!

이 부분이 궁금한데요,
`router.patch("/deleteReply", async (req, res) => {
    const { replyId, showing } = req.body;
    console.log(replyId);
    await Reply.updateOne({_id: replyId},{$set : {showing}});
    res.send({ result: "success" });
  });`
  
 왜 delete 메소드가 아닌 patch 메소드를 사용하여 삭제 기능을 구현하셨나요?

**Comment by fnrkp089** [comment]
안녕하세요, delete로 바로 삭제하는것이 아니라 patch로 속성변화로 삭제를 구현하셧는지 궁금하셔서 답변남깁니다

일단 몇가지 이점을 생각할수 있는데요,
실제 데이터를 삭제하지 않고 화면단에서 그려줄때 해당데이터를 삭제하지 않음으로
나중에 해당 데이터가 필요할때 빠르고 쉽게 데이터를 복구하거나 참고할수 있습니다

그리고 만일 index와 같이 데이터에 번호를 먹였을때 해당 데이터가 사라지면 그 번호가 사라져서 나중에 오류가 발생할 수 있기에 데이터의 순서도 보장할 수 있게 해줍니다

데이터의 무결성보장과, 후에 추가되거나 참조할 일이 존재할때 쉽게 데이터를 조작할수 있는 장점은 삭제된 데이터를 더미형식 데이터 형태로 남겨두어 데이터베이스의 용량을 차지하는 단점보다 더 우수하다고 생각하여 delete로 날려버리지않고 그냥 속성변경 쿼리를 날리는 형태로 구현하였습니다

도움이 되셨으면 좋겠습니다
