### ISSUE TITLE
잘보고갑니당!

### ISSUE THREAD

**Issue by changchanghwang** [fnrkp089/Han_M_1#2]
잘보고갑니다!
잘만드셨네영ㅋㅋㅋㅋ 다만 로그인할때 벨리데이션에서

비밀번호에 아이디가 포함되었을때가 빠진것 같아서 이슈남깁니다!

코드도 깔끔하고 되게 좋네영 ㅎ

**Comment by fnrkp089** [comment]
mysql포팅하다가 터져서 부랴부랴 다시 끌어모으고 붙이느라 정신없는 코드셨을텐데 ㅋㅋㅋ
감사드립니다!
저도 XSS공격하러 가겟습니다...!
