### ISSUE TITLE
엄청 깔끔하네요! 잘보고가요 ;)

### ISSUE THREAD

**Issue by sparta-jason** [fnrkp089/Han_M_1#3]
잘만드신 것 같아요!! 구경 잘하구 갑니다 ㅎㅎㅎ
포스팅, 댓글 입력 시 줄바꿈하면 출력 시에도 적용되면 더 좋을 것 같아요!

한 주간 고생하셨습니다 짝짝!

**Comment by fnrkp089** [comment]
감사드립니다 ㅜㅜ 
mysql로 포팅하다가 터져가지고 부랴부랴 다시 주워모았는데
다음에는 더 확실히 하겠습니다!
